# Generated by Django 5.2 on 2025-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('puzzle_question', models.TextField()),
                ('puzzle_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
