# Generated by Django 5.2 on 2026-03-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0002_room_hint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='room',
            name='alternate_answers',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of additional accepted answers (case-insensitive).'),
        ),
        migrations.AddField(
            model_name='room',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order of this room (lowest first).'),
        ),
    ]
