# Generated by Django 5.2 on 2026-03-03 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0004_add_gamesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
