# Generated by Django 5.2 on 2026-03-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0005_gamesession_started_at_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Suggested display order.')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('puzzle_question', models.TextField()),
                ('puzzle_answer', models.CharField(max_length=100)),
                ('alternate_answers', models.TextField(blank=True, default='', help_text='Comma-separated list of additional accepted answers (case-insensitive).')),
                ('hint', models.TextField(blank=True, default='No hint available.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
