# Generated by Django 5.2 on 2026-03-05 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escape", "0005_gamesession_started_at_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("puzzle_question", models.TextField()),
                ("puzzle_answer", models.CharField(max_length=100)),
                (
                    "alternate_answers",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of additional accepted answers.",
                    ),
                ),
                ("hint", models.TextField(blank=True, default="No hint available.")),
                (
                    "generation_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The prompt or parameters used to generate this puzzle.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_puzzles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Puzzle",
                "verbose_name_plural": "Generated Puzzles",
                "ordering": ["-created_at"],
            },
        ),
    ]
